
name: Build Avrdude 

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download avrdude release
      uses: actions/checkout@v2
      with:
        repository: arduino/avrdude-build-script
        ref: 6.3.0-arduino19
    - name: Download release artefacts
      run: |
        curl https://github.com/arduino/avrdude-build-script/releases/download/6.3.0-arduino19/avrdude-6.3.0-arduino19-x86_64-pc-linux-gnu.tar.bz2
    - name: See what we have
      run: |
        pwd
        ls -la
