
name: Build Avrdude 

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download avrdude release artefacts
      run: |
        curl -L https://github.com/arduino/avrdude-build-script/releases/download/6.3.0-arduino19/avrdude-6.3.0-arduino19-x86_64-pc-linux-gnu.tar.bz2 -o avrdude-linux-6.3.0.tar.bz2
        mkdir avrdude-linux
        tar -xf avrdude-linux-6.3.0.tar.bz2 -C avrdude-linux
        curl -L https://github.com/arduino/avrdude-build-script/releases/download/6.3.0-arduino19/avrdude-6.3.0-arduino19-x86_64-apple-darwin12.tar.bz2 -o avrdude-macos-6.3.0.tar.bz2
        mkdir avrdude-macos
        tar -xf avrdude-macos-6.3.0.tar.bz2 -C avrdude-macos
        curl -L https://github.com/arduino/avrdude-build-script/releases/download/6.3.0-arduino19/avrdude-6.3.0-arduino19-i686-w64-mingw32.zip -o  avrdude-win-6.3.0.zip
        mkdir avrdude-win
        unzip avrdude-win-6.3.0.zip -d avrdude-win
    - name: See what we have 1
      run: |
        pwd
        ls -la
    - name: Repackage avrdude
      run: |
        mkdir avrdude
        mv avrdude-linux avrdude
        mv avrdude-macos avrdude
        mv avrdude-win avrdude
        ls -la avrdude
    - name: Upload avrdude artifact
      uses: actions/upload-artifact@v2
      with:
        name: avrdude
        path: |
            avrdude/*
  package-cs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [Mega, Uno, Nano]
    steps:
      - name: Get avrdude artifact
        uses: actions/download-artifact@v2
        with:
          name: avrdude
          path: /home/runner/work/BuildDccEX/avrdude
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          workflow: build_dccex_cs.yml
          name: Arduino${{matrix.board}}
          path: /home/runner/work/BuildDccEX/Arduino${{matrix.board}}
        # Optional, defaults to current repo
          repo: ${{github.repository}}
      - name: See what we have 2
        run: |
          cd /home/runner/work/BuildDccEX/Arduino${{matrix.board}}
          pwd
          ls -la
      - name: Package commandstation & avrdude
        uses: actions/upload-artifact@v2
        with:
          name: Avr_Arduino${{matrix.board}}
          path: |
              /home/runner/work/BuildDccEX/avrdude/*
              /home/runner/work/BuildDccEX/Arduino${{matrix.board}}/*
      
