
name: Build Avrdude 

on:
  #schedule:
    # * is a special character in YAML so you have to quote this string rune every day at 2 am
    #- cron:  '0 2 * * *'
  push:
    branches: 
      - main
       

jobs:
  prepare-avrdude:
    runs-on: ubuntu-latest
    steps:
    - name: Download avrdude release artefacts
      run: |
        curl -L https://github.com/arduino/avrdude-build-script/releases/download/6.3.0-arduino19/avrdude-6.3.0-arduino19-x86_64-pc-linux-gnu.tar.bz2 -o avrdude-linux-6.3.0.tar.bz2
        mkdir avrdude-linux
        tar -xf avrdude-linux-6.3.0.tar.bz2 -C avrdude-linux
        curl -L https://github.com/arduino/avrdude-build-script/releases/download/6.3.0-arduino19/avrdude-6.3.0-arduino19-x86_64-apple-darwin12.tar.bz2 -o avrdude-macos-6.3.0.tar.bz2
        mkdir avrdude-macos
        tar -xf avrdude-macos-6.3.0.tar.bz2 -C avrdude-macos
        curl -L https://github.com/arduino/avrdude-build-script/releases/download/6.3.0-arduino19/avrdude-6.3.0-arduino19-i686-w64-mingw32.zip -o  avrdude-win-6.3.0.zip
        mkdir avrdude-win
        unzip avrdude-win-6.3.0.zip -d avrdude-win
    - name: See what we have 1
      run: |
        pwd
        ls -la
    - name: Repackage avrdude
      run: |
        pwd
        mkdir avrdude && mkdir avrdude/win && mkdir avrdude/linux && mkdir avrdude/macos
        ls -la avrdude
        ls -la avrdude-linux/avrdude/* 
        ls -la avrdude-macos/avrdude/*
        ls -la avrdude-win avrdude/*

        # mv avrdude-linux/avrdude/* avrdude/linux
        # mv avrdude-macos/avrdude/* avrdude/macos
        # mv avrdude-win avrdude/* avrdude/win
        ls -la avrdude
    - name: Upload avrdude artifact
      uses: actions/upload-artifact@v2
      with:
        name: avrdude
        path: |
            avrdude/*
  package-cs:
    needs: prepare-avrdude
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [Mega, Uno, Nano]
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          workflow: build_dccex_cs.yml
          name: Arduino${{matrix.board}}
          path: /home/runner/work/BuildDccEX/Arduino${{matrix.board}}
        # Optional, defaults to current repo
          repo: ${{github.repository}}
      - name: Get avrdude artifact
        uses: actions/download-artifact@v2
        with:
          name: avrdude
          path: /home/runner/work/BuildDccEX/avrdude    
      - name: See what we have 2
        run: |
          ls -la /home/runner/work/BuildDccEX/avrdude
          ls -la /home/runner/work/BuildDccEX/Arduino${{matrix.board}}
          
      - name: Package commandstation & avrdude
        uses: actions/upload-artifact@v2
        with:
          name: Avr_Arduino${{matrix.board}}
          path: |
              /home/runner/work/BuildDccEX/avrdude/*
              /home/runner/work/BuildDccEX/Arduino${{matrix.board}}/*
      
