name: Release DccEX Avrdude 

on:
  push:
    branches: 
      - main
  tags: 
    - 'v*'

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [Mega, Uno, Nano]
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          workflow: build_dccex_cs.yml
          name: Avr_Arduino${{matrix.board}}
          path: /home/runner/work/BuildDccEX/Arduino${{matrix.board}}
        # Optional, defaults to current repo
          repo: ${{github.repository}} 
      - name: See what we have 2
        run: |
          ls -la /home/runner/work/BuildDccEX
         
